apiVersion: apps/v1
kind: Deployment
metadata:
  name: safe-as-houses-api-deployment
  labels:
    app: safe-as-houses-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: safe-as-houses-api
  template:
    metadata:
      labels:
        app: safe-as-houses-api
    spec:
      containers:
        - name: safe-as-houses-api
          image: 426038099359.dkr.ecr.eu-west-2.amazonaws.com/safe-as-houses:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-server
            - containerPort: 9090
              name: grpc-server
