// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: service_safe_as_houses.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SafeAsHouses_CreateUser_FullMethodName = "/pb.SafeAsHouses/CreateUser"
	SafeAsHouses_LoginUser_FullMethodName  = "/pb.SafeAsHouses/LoginUser"
)

// SafeAsHousesClient is the client API for SafeAsHouses service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SafeAsHousesClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type safeAsHousesClient struct {
	cc grpc.ClientConnInterface
}

func NewSafeAsHousesClient(cc grpc.ClientConnInterface) SafeAsHousesClient {
	return &safeAsHousesClient{cc}
}

func (c *safeAsHousesClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, SafeAsHouses_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safeAsHousesClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, SafeAsHouses_LoginUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SafeAsHousesServer is the server API for SafeAsHouses service.
// All implementations must embed UnimplementedSafeAsHousesServer
// for forward compatibility
type SafeAsHousesServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedSafeAsHousesServer()
}

// UnimplementedSafeAsHousesServer must be embedded to have forward compatible implementations.
type UnimplementedSafeAsHousesServer struct {
}

func (UnimplementedSafeAsHousesServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSafeAsHousesServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedSafeAsHousesServer) mustEmbedUnimplementedSafeAsHousesServer() {}

// UnsafeSafeAsHousesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SafeAsHousesServer will
// result in compilation errors.
type UnsafeSafeAsHousesServer interface {
	mustEmbedUnimplementedSafeAsHousesServer()
}

func RegisterSafeAsHousesServer(s grpc.ServiceRegistrar, srv SafeAsHousesServer) {
	s.RegisterService(&SafeAsHouses_ServiceDesc, srv)
}

func _SafeAsHouses_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeAsHousesServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SafeAsHouses_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeAsHousesServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SafeAsHouses_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafeAsHousesServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SafeAsHouses_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafeAsHousesServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SafeAsHouses_ServiceDesc is the grpc.ServiceDesc for SafeAsHouses service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SafeAsHouses_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SafeAsHouses",
	HandlerType: (*SafeAsHousesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _SafeAsHouses_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _SafeAsHouses_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_safe_as_houses.proto",
}
